# -*- coding: utf-8 -*-
"""tennis_ball_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WM_Of-KP2CERpWbHj6j5JpbFhwGw6yRs
"""

from ultralytics import YOLO

model = YOLO('yolov8x')

result = model.predict('input_videos/input_video.mp4', save=True)
print(result)

"""# Get Dataset"""

from roboflow import Roboflow
rf = Roboflow(api_key="hamC2hPywmRj4frv0kbV")
project = rf.workspace("viren-dhanwani").project("tennis-ball-detection")
version = project.version(6)
dataset = version.download("yolov5")

import shutil
shutil.move("tennis-ball-detection-6/train",
            "tennis-ball-detection-6/tennis-ball-detection-6/train",
            )
shutil.move("tennis-ball-detection-6/test",
            "tennis-ball-detection-6/tennis-ball-detection-6/test",
            )
shutil.move("tennis-ball-detection-6/valid",
            "tennis-ball-detection-6/tennis-ball-detection-6/valid",
            )

!yolo task=detect mode=train model=yolov5l6u.pt data={dataset.location}/data.yaml epochs=10 imgsz=640